### PR TITLE
Add missing emphasis to chapter 2

### PR DESCRIPTION
**Pull request by robinwhittleton**
Reported by Rand Brittain and checked against source scans

### CODE REVIEW

**Comment by acabal** [comment]
Thanks! Did you have a chance to check the rest of the scans for italics too?

**Comment by robinwhittleton** [comment]
Will double-check now.

**Comment by robinwhittleton** [comment]
OK, found a couple more missing emphases and one piece of missing newspaper markup.

**Comment by acabal** [comment]
Great, thanks!

**Pull request merged**
